### ISSUE TITLE
Print ignores functions

### ISSUE THREAD

**Issue by fmease** [Ratstail91/Toy#1]
The built-in `print` does not print anything at all (not even a line break) if the argument is of
type function. I expected it to either print a debug representation (like `<function>`) or throw an error that there is no suitable representation.

Example:
```
print("alpha");
print(x => x);
print("omega");
```
This prints:
```
alpha
omega
```

**Comment by Ratstail91** [comment]
Thanks @fmease I'll look into this when I get the chance. Sorry for not noticing this issue earlier.

**Comment by Ratstail91** [comment]
The problem wasn't in the Toy engine itself, but rather the website.

The website uses a tool called [DOMPurify](https://github.com/cure53/DOMPurify) to eliminate XSS security problems. The intended behaviour of `print x => x;` is to print out `<function>`, which resembles a HTML tag, thus DOMPurify removed it from the output just before it reached the user.

DOMPurify was and is working correctly. I've simply altered the server-side node runner to replace the characters `<` and `>` with `&lt;` and `&gt;` respectfully. Now the intended behaviour is working correctly.

I should also note that I've moved the definitions of `ToString` to the top of each functor and plugin class, so that they're easy to spot - it's usually only one line long, so could be lost among the 100+ lines of code.
